create extension if not exists pg_trgm;
create table message (id bigint not null, instant timestamp(6) with time zone, message text, room_id bigint, primary key (id));
create table participant (id bigserial not null, chat_allowed boolean, video_allowed boolean, voice_allowed boolean, volume integer, user_id bigint, participants_id bigint, primary key (id));
create table person (id bigint not null, name varchar(255), primary key (id));
create table playlist (id bigint not null, name text, primary key (id));
create table room (id bigint not null, name text, preview_url text, session_id text, host_id bigserial, playlist_id bigint, primary key (id));
create table track (id bigint not null, author text, file_name text, name text, preview_url text, tracks_id bigint, primary key (id));
create table users (id bigint not null, avatar_url text, email text not null, password text not null, username text not null, primary key (id));
alter table if exists room drop constraint if exists UK_ro2nhs1k2482cogc40ea4xibh;
alter table if exists room add constraint UK_ro2nhs1k2482cogc40ea4xibh unique (session_id);
alter table if exists users drop constraint if exists UK_6dotkott2kjsp8vw4d0m25fb7;
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users drop constraint if exists UK_r43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
create sequence message_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence playlist_seq start with 1 increment by 50;
create sequence room_seq start with 1 increment by 50;
create sequence track_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
alter table if exists message add constraint FKl1kg5a2471cv6pkew0gdgjrmo foreign key (room_id) references room;
alter table if exists participant add constraint FK5mkbmcdbhnooj3v3ubcnreah9 foreign key (user_id) references users;
alter table if exists participant add constraint FKks01cgn56yqtca7mpxdlbnxjx foreign key (participants_id) references room;
alter table if exists room add constraint FKhhw5iwi8vxmjh7wt5ktswdhrv foreign key (host_id) references participant;
alter table if exists room add constraint FKi2bwm6n9bd9by4x7p8my6hfs0 foreign key (playlist_id) references playlist;
alter table if exists track add constraint FK7fos2x17ukkycb9sykw2mfffs foreign key (tracks_id) references playlist;
create table message (id bigint not null, instant timestamp(6) with time zone, message text, room_id bigint, primary key (id));
create table participant (id bigserial not null, chat_allowed boolean, video_allowed boolean, voice_allowed boolean, volume integer, user_id bigint, participants_id bigint, primary key (id));
create table person (id bigint not null, name varchar(255), primary key (id));
create table playlist (id bigint not null, name text, primary key (id));
create table room (id bigint not null, name text, preview_url text, session_id text, host_id bigserial, playlist_id bigint, primary key (id));
create table track (id bigint not null, author text, file_name text, name text, preview_url text, tracks_id bigint, primary key (id));
create table users (id bigint not null, avatar_url text, email text not null, password text not null, username text not null, primary key (id));
alter table if exists room drop constraint if exists UK_ro2nhs1k2482cogc40ea4xibh;
alter table if exists room add constraint UK_ro2nhs1k2482cogc40ea4xibh unique (session_id);
alter table if exists users drop constraint if exists UK_6dotkott2kjsp8vw4d0m25fb7;
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users drop constraint if exists UK_r43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists message add constraint FKl1kg5a2471cv6pkew0gdgjrmo foreign key (room_id) references room;
alter table if exists participant add constraint FK5mkbmcdbhnooj3v3ubcnreah9 foreign key (user_id) references users;
alter table if exists participant add constraint FKks01cgn56yqtca7mpxdlbnxjx foreign key (participants_id) references room;
alter table if exists room add constraint FKhhw5iwi8vxmjh7wt5ktswdhrv foreign key (host_id) references participant;
alter table if exists room add constraint FKi2bwm6n9bd9by4x7p8my6hfs0 foreign key (playlist_id) references playlist;
alter table if exists track add constraint FK7fos2x17ukkycb9sykw2mfffs foreign key (tracks_id) references playlist;
create sequence message_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence playlist_seq start with 1 increment by 50;
create sequence room_seq start with 1 increment by 50;
create sequence track_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
create table message (id bigint not null, instant timestamp(6) with time zone, message text, room_id bigint, primary key (id));
create table participant (id bigserial not null, chat_allowed boolean, video_allowed boolean, voice_allowed boolean, volume integer, user_id bigint, participants_id bigint, primary key (id));
create table person (id bigint not null, name varchar(255), primary key (id));
create table playlist (id bigint not null, name text, primary key (id));
create table room (id bigint not null, name text, preview_url text, session_id text, host_id bigserial, playlist_id bigint, primary key (id));
create table track (id bigint not null, author text, file_name text, name text, preview_url text, tracks_id bigint, primary key (id));
create table users (id bigint not null, avatar_url text, email text not null, password text not null, username text not null, primary key (id));
alter table if exists room drop constraint if exists UK_ro2nhs1k2482cogc40ea4xibh;
alter table if exists room add constraint UK_ro2nhs1k2482cogc40ea4xibh unique (session_id);
alter table if exists users drop constraint if exists UK_6dotkott2kjsp8vw4d0m25fb7;
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users drop constraint if exists UK_r43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
create sequence message_seq start with 1 increment by 50;
create sequence person_seq start with 1 increment by 50;
create sequence playlist_seq start with 1 increment by 50;
create sequence room_seq start with 1 increment by 50;
create sequence track_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
alter table if exists message add constraint FKl1kg5a2471cv6pkew0gdgjrmo foreign key (room_id) references room;
alter table if exists participant add constraint FK5mkbmcdbhnooj3v3ubcnreah9 foreign key (user_id) references users;
alter table if exists participant add constraint FKks01cgn56yqtca7mpxdlbnxjx foreign key (participants_id) references room;
alter table if exists room add constraint FKhhw5iwi8vxmjh7wt5ktswdhrv foreign key (host_id) references participant;
alter table if exists room add constraint FKi2bwm6n9bd9by4x7p8my6hfs0 foreign key (playlist_id) references playlist;
alter table if exists track add constraint FK7fos2x17ukkycb9sykw2mfffs foreign key (tracks_id) references playlist;
create sequence participant_seq start with 1 increment by 50;

